<?php
/** @package Empresax::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ReciboMap.php");

/**
 * ReciboDAO provides object-oriented access to the recibo table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Empresax::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ReciboDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $Data;

	/** @var int */
	public $ServicoId;

	/** @var int */
	public $ClienteId;


	/**
	 * Returns the foreign object based on the value of ClienteId
	 * @return Cliente
	 */
	public function GetCliente()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_recibo_paciente");
	}

	/**
	 * Returns the foreign object based on the value of ServicoId
	 * @return Servico
	 */
	public function GetServico()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_recibo_servico");
	}


}
?>